window.BREW_HELP_SYNONYMS = {
  ajuda: ['help', 'suporte', 'central', 'documentacao', 'documentação'],
  problema: ['erro', 'falha', 'bug', 'nao funciona', 'não funciona'],
  barris: ['barril', 'keg', 'kegs', 'ativos'],
  estoque: ['almoxarifado', 'insumos', 'inventario', 'inventário'],
  vendas: ['comercial', 'pedido', 'pedidos', 'cliente', 'clientes'],
  logistica: ['logística', 'entrega', 'entregas', 'rota', 'rotas'],
  producao: ['produção', 'lote', 'lotes', 'brew day'],
  financeiro: ['caixa', 'receita', 'receitas'],
  brewpub: ['bar', 'pdv', 'comanda', 'comandas'],
  acesso: ['login', 'entrar', 'senha', 'sessao', 'sessão']
};

window.BREW_HELP_INDEX = [
  {id:'usar-central',title:'Como usar a Central de Ajuda',aliases:['como funciona a ajuda','começar na central','navegar na ajuda'],tasks:['encontrar conteúdo','pesquisar','navegar'],description:'Entenda a organização da Central, como pesquisar e como identificar conteúdo revisado.',module:'Central de Ajuda',roles:['todos'],tags:['primeiros passos','busca','documentação'],content:'A Central prioriza tarefas, módulos, papéis e resolução de problemas. Conteúdo operacional só entra após revisão documental.',href:'artigo.html?demo=usar-central',status:'Conteúdo seguro'},
  {id:'status-conteudo',title:'Como identificar conteúdo revisado',aliases:['verified','verificado','última revisão','ultima revisao'],tasks:['conferir validade','conferir revisão'],description:'Veja como data de revisão, status editorial e origem serão apresentados nos artigos da Central.',module:'Central de Ajuda',roles:['todos'],tags:['source of truth','revisão','governança'],content:'Artigos operacionais futuros terão origem, revisão e status explícitos. A fundação atual não publica procedimentos não auditados.',href:'conceitos.html#conteudo-verificado',status:'Conteúdo seguro'},
  {id:'resolver-problema',title:'Resolver problemas: por onde começar',aliases:['erro','falha','deu errado','não funciona','nao funciona'],tasks:['diagnosticar problema','registrar erro','buscar solução'],description:'Um roteiro neutro para registrar contexto e encontrar a categoria correta de suporte, sem alterar dados.',module:'Resolver problemas',roles:['todos'],tags:['troubleshooting','diagnóstico','suporte'],content:'Identifique a área, registre a mensagem exibida e procure pelo termo exato. Procedimentos específicos do produto dependem de conteúdo auditado.',href:'troubleshooting.html',status:'Conteúdo seguro'},
  {id:'hub-producao',title:'Produção — hub do módulo',aliases:['produção','lote','lotes','brew day','tanque'],tasks:['encontrar ajuda de produção'],description:'Entrada da documentação de Produção. Os procedimentos operacionais ainda aguardam auditoria documental.',module:'Produção',roles:['produção','gestor'],tags:['módulo','em preparação'],content:'Hub estrutural para artigos futuros de Produção. Nenhum passo operacional é tratado como vigente nesta versão.',href:'modulo.html?m=producao',status:'Estrutura pronta'},
  {id:'hub-estoque',title:'Estoque e Almoxarifado — hub do módulo',aliases:['estoque','almoxarifado','insumos','inventário','inventario'],tasks:['encontrar ajuda de estoque'],description:'Entrada da documentação de Estoque e Almoxarifado, sem procedimentos operacionais não auditados.',module:'Estoque e Almoxarifado',roles:['almoxarifado','produção','gestor'],tags:['módulo','em preparação'],content:'Hub estrutural preparado para artigos verificados após a auditoria documental.',href:'modulo.html?m=estoque',status:'Estrutura pronta'},
  {id:'hub-ativos',title:'Ativos e Barris — hub do módulo',aliases:['ativos','barris','barril','keg','kegs','chopeira','cilindro'],tasks:['encontrar ajuda de barris','encontrar ajuda de ativos'],description:'Entrada da documentação de Ativos e Barris. Conteúdo operacional será adicionado somente após validação.',module:'Ativos e Barris',roles:['logística','comercial','gestor'],tags:['módulo','rastreabilidade','em preparação'],content:'Hub estrutural. Não descreve movimentações, estados ou regras reais do produto nesta etapa.',href:'modulo.html?m=ativos',status:'Estrutura pronta'},
  {id:'hub-comercial',title:'Comercial — hub do módulo',aliases:['comercial','vendas','pedido','pedidos','cliente','clientes'],tasks:['encontrar ajuda comercial'],description:'Entrada da documentação Comercial preparada para receber artigos auditados.',module:'Comercial',roles:['comercial','gestor'],tags:['módulo','em preparação'],content:'Nenhum fluxo de pedido ou venda é publicado como procedimento nesta fundação.',href:'modulo.html?m=comercial',status:'Estrutura pronta'},
  {id:'hub-logistica',title:'Logística — hub do módulo',aliases:['logística','logistica','entrega','entregas','rota','rotas'],tasks:['encontrar ajuda de logística'],description:'Entrada da documentação de Logística, ainda sem instruções de entrega ou devolução.',module:'Logística',roles:['logística','comercial','gestor'],tags:['módulo','em preparação'],content:'Estrutura destinada a artigos futuros. Fluxos reais aguardam auditoria documental.',href:'modulo.html?m=logistica',status:'Estrutura pronta'},
  {id:'hub-financeiro',title:'Financeiro — hub do módulo',aliases:['financeiro','caixa','receita','receitas'],tasks:['encontrar ajuda financeira'],description:'Entrada da documentação Financeira, sem procedimentos de caixa ou lançamentos.',module:'Financeiro',roles:['financeiro','gestor'],tags:['módulo','em preparação'],content:'Hub estrutural preparado para conteúdo verificado. Não publica regras financeiras do sistema.',href:'modulo.html?m=financeiro',status:'Estrutura pronta'},
  {id:'hub-brewpub',title:'Brewpub — hub do módulo',aliases:['brewpub','bar','pdv','comanda','comandas'],tasks:['encontrar ajuda do brewpub'],description:'Entrada da documentação de Brewpub, sem instruções de caixa, comandas ou atendimento.',module:'Brewpub',roles:['atendimento','gestor'],tags:['módulo','em preparação'],content:'Hub estrutural. Procedimentos reais entram somente após os gates documentais.',href:'modulo.html?m=brewpub',status:'Estrutura pronta'},
  {id:'hub-fiscal',title:'Fiscal — hub do módulo',aliases:['fiscal','nota fiscal','nfe','nf-e','nfce','nfc-e'],tasks:['encontrar ajuda fiscal'],description:'Entrada estrutural para documentação Fiscal. Nenhuma orientação fiscal de produção é publicada aqui.',module:'Fiscal',roles:['financeiro','gestor'],tags:['módulo','homologação','em preparação'],content:'A Central não publica procedimentos fiscais nesta etapa. O conteúdo depende de revisão e homologação próprias.',href:'modulo.html?m=fiscal',status:'Estrutura pronta'},
  {id:'hub-pdv-mobile',title:'PDV Mobile — hub do módulo',aliases:['pdv mobile','ponto parceiro','parceiro'],tasks:['encontrar ajuda do pdv mobile'],description:'Entrada estrutural para documentação de PDV Mobile, sem procedimentos de operação.',module:'PDV Mobile',roles:['ponto parceiro','comercial','gestor'],tags:['módulo','em preparação'],content:'Hub estrutural. Instruções de uso ainda não foram publicadas nesta Central.',href:'modulo.html?m=pdv-mobile',status:'Estrutura pronta'},
  {id:'conceitos-central',title:'Conceitos importantes da Central de Ajuda',aliases:['glossário','glossario','conceitos','termos'],tasks:['entender documentação'],description:'Glossário editorial da própria Central: módulo, tarefa, artigo verificado, última revisão e fonte de verdade.',module:'Conceitos importantes',roles:['todos'],tags:['glossário','governança'],content:'Conceitos editoriais e de navegação; não substituem definições operacionais do BrewControl.',href:'conceitos.html',status:'Conteúdo seguro'},
  {id:'mudancas-central',title:'O que mudou na Central de Ajuda',aliases:['novidades','release notes','mudanças','mudancas'],tasks:['ver mudanças da ajuda'],description:'Histórico público da própria Central de Ajuda e de sua estrutura documental.',module:'O que mudou',roles:['todos'],tags:['release notes','central de ajuda'],content:'A versão de fundação cria busca, hubs e templates sem publicar procedimentos operacionais não auditados.',href:'novidades.html',status:'Conteúdo seguro'}
];